name: Trigger Vercel Rebuild

on:
    push:
        branches: [main]
        paths: ["articles/**"]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Wait before deployment
              run: sleep 30
            - name: Trigger Vercel Deploy Hook
              run: curl -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}"
